version: '3'
services:
  mongo:
    image: "mongo:4.4"
    restart: always
    #ports:
    #  - "27017:27017"
    volumes:
      - ./data/mongo/db:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      - sclab-network

  mail:
    image: "bytemark/smtp"
    restart: always
    #ports:
    #  - "25:25"
    networks:
      - sclab-network
  
  redis:
    image: "bitnami/redis:7.0.9"
    #ports:
    #  - "6379:6379"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      - sclab-network

  qdrant:
    image: "qdrant/qdrant:v1.7.0"
    #ports:
    # - "6333:6333"
    restart: always
    volumes:
      - ./data/qdrant:/qdrant/storage
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      - sclab-network

  webapp:
    image: "sclabio/webapp:1.0.0"
    restart: always
    ports:
      - "80"
    volumes:
      - ./data/webapp:/data
      - ./data/webapp/logs:/data/logs
      - ./data/webapp/files:/data/files
      - ./jwt:/data/jwt
      - ./cert:/data/cert
    env_file:
      - ./common.env
      - ./webapp.env
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
    links:
      - mongo
      - redis
      - qdrant
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis
      - qdrant
    networks:
      - sclab-network

  gis-process:
    image: "sclabio/gis-process:1.0.0"
    restart: always
    volumes:
      - ./data/gis-process/logs:/data/logs
    env_file:
      - ./common.env
      - ./gis-process.env
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
    links:
      - mongo
      - redis
      - webapp
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis
    networks:
      - sclab-network
  
  mqtt-client:
    image: "sclabio/mqtt-client:1.0.0"
    restart: always
    volumes:
      - ./data/mqtt-client/logs:/data/logs
    env_file:
      - ./common.env
      - ./mqtt-client.env
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
    links:
      - mongo
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis
    networks:
      - sclab-network
      
  mqtt-broker:
    image: "sclabio/mqtt-broker:1.0.0"
    restart: always
    ports:
      - "8883:8883"
      - "8888:8888"
    volumes:
      - ./data/mqtt-broker/logs:/data/logs
      - ./cert:/data/cert
      - ./jwt:/data/jwt
    env_file:
      - ./common.env
      - ./mqtt-broker.env
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
    links:
      - mongo
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis
    networks:
      - sclab-network
      
  kafka-client:
    image: "sclabio/kafka-client:1.0.0"
    restart: always
    volumes:
      - ./data/kafka-client/logs:/data/logs
    env_file:
      - ./common.env
      - ./kafka-client.env
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
    links:
      - mongo
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis
    networks:
      - sclab-network
  
  ai-service:
    image: "sclabio/ai-service:1.0.0"
    restart: always
    volumes:
      - ./data/ai-service/logs:/data/logs
    env_file:
      - ./common.env
      - ./ai-service.env
    links:
      - mongo
      - redis
      - qdrant
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis
      - qdrant
    networks:
      - sclab-network

  sclab-proxy:
    image: nginx:alpine3.18
    ports:
      - '80:80'
      - '443:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    depends_on:
      - webapp
    networks:
      - sclab-network
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

networks:
  sclab-network:
    external: true
