version: '3'
services:
  mongo:
    image: "mongo:4.4"
    restart: always
    #ports:
    #  - "27017:27017"
    volumes:
      - ./data/mongo/db:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  mail:
    image: "bytemark/smtp"
    restart: always
    #ports:
    #  - "25:25"

  redis:
    image: "bitnami/redis:latest"
    #ports:
    #  - "6379:6379"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

  webapp:
    image: "sclabio/webapp:1.0.0"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/webapp:/data
      - ./data/webapp/logs:/data/logs
      - ./data/webapp/files:/data/files
      - ./jwt:/data/jwt
    env_file:
      - ./common.env
      - ./webapp.env
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
    links:
      - mongo
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis

  gis-process:
    image: "sclabio/gis-process:1.0.0"
    restart: always
    volumes:
      - ./data/gis-process/logs:/data/logs
    env_file:
      - ./common.env
      - ./gis-process.env
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
    links:
      - mongo
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis

  mqtt-client:
    image: "sclabio/mqtt-client:1.0.0"
    restart: always
    volumes:
      - ./data/mqtt-client/logs:/data/logs
    env_file:
      - ./common.env
      - ./mqtt-client.env
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
    links:
      - mongo
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis

  mqtt-broker:
    image: "sclabio/mqtt-broker:1.0.0"
    restart: always
    ports:
      - "8883:8883"
      - "8888:8888"
    volumes:
      - ./data/mqtt-broker/logs:/data/logs
      - ./cert:/data/cert
      - ./jwt:/data/jwt
    env_file:
      - ./common.env
      - ./mqtt-broker.env
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
    links:
      - mongo
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis
  
  kafka-client:
    image: "sclabio/kafka-client:1.0.0"
    restart: always
    volumes:
      - ./data/kafka-client/logs:/data/logs
    env_file:
      - ./common.env
      - ./kafka-client.env
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
    links:
      - mongo
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis

networks:
  sclab-network:
    external: true