services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: changeMePLZ
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data/mongo/db:/data/db
    command: mongod --replSet rs0 --bind_ip_all
    networks:
      - sclab-network

  mail:
    image: "bytemark/smtp"
    restart: always
    networks:
      - sclab-network

  redis:
    image: "bitnami/redis:7.0.9"
    ports:
     - "6379:6379"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      - sclab-network

  qdrant:
    image: "qdrant/qdrant:v1.7.0"
    ports:
    - "6333:6333"
    restart: always
    volumes:
      - ./data/qdrant:/qdrant/storage
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      - sclab-network

  webapp:
    image: "873379329511.dkr.ecr.ap-northeast-2.amazonaws.com/sclabio/onpremise-webapp:latest"
    restart: always
    ports:
      - "80"
    volumes:
      - ./data/webapp:/data
      - ./data/webapp/logs:/data/logs
      - ./data/webapp/files:/data/files
      - ./jwt:/data/jwt
      - ./cert:/data/cert
    env_file:
      - ./common.env
      - ./webapp.env
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis
      - qdrant
    networks:
      - sclab-network

  gis-process:
    image: "873379329511.dkr.ecr.ap-northeast-2.amazonaws.com/sclabio/onpremise-gis-process:latest"
    restart: always
    volumes:
      - ./data/gis-process/logs:/data/logs
    env_file:
      - ./common.env
      - ./gis-process.env
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis
      - webapp
    networks:
      - sclab-network

  mqtt-client:
    image: "873379329511.dkr.ecr.ap-northeast-2.amazonaws.com/sclabio/onpremise-mqtt-client:latest"
    restart: always
    volumes:
      - ./data/mqtt-client/logs:/data/logs
    env_file:
      - ./common.env
      - ./mqtt-client.env
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis
      - webapp
    networks:
      - sclab-network
      
  mqtt-broker:
    image: "873379329511.dkr.ecr.ap-northeast-2.amazonaws.com/sclabio/onpremise-mqtt-broker:latest"
    restart: always
    ports:
      - "8883:8883"
      - "8888:8888"
    volumes:
      - ./data/mqtt-broker/logs:/data/logs
      - ./cert:/data/cert
      - ./jwt:/data/jwt
    env_file:
      - ./common.env
      - ./mqtt-broker.env
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis
      - webapp
    networks:
      - sclab-network
      
  kafka-client:
    image: "873379329511.dkr.ecr.ap-northeast-2.amazonaws.com/sclabio/onpremise-kafka-client:latest"
    restart: always
    volumes:
      - ./data/kafka-client/logs:/data/logs
    env_file:
      - ./common.env
      - ./kafka-client.env
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis
      - webapp
    networks:
      - sclab-network
  
  ai-service:
    image: "873379329511.dkr.ecr.ap-northeast-2.amazonaws.com/sclabio/onpremise-ai-service:latest"
    restart: always
    volumes:
      - ./data/ai-service/logs:/app/dist/utils/data/logs
    env_file:
      - ./common.env
      - ./ai-service.env
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis
      - qdrant
      - webapp
    networks:
      - sclab-network
      
  sclab-proxy:
    image: nginx:alpine3.18
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    depends_on:
      - webapp
    networks:
      - sclab-network
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

networks:
  sclab-network:
    external: true
