services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: "mongo:4.4"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo/db:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      - sclab-network

  mail:
    container_name: mail
    hostname: mail
    image: "bytemark/smtp"
    restart: always
    networks:
      - sclab-network

  redis:
    container_name: redis
    hostname: redis
    image: "bitnami/redis:7.4.1"
    ports:
      - "6379:6379"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_ALLOW_REMOTE_CONNECTIONS=yes
      - REDIS_PASSWORD=changeThisRedisPassword
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      - sclab-network

  qdrant:
    container_name: qdrant
    hostname: qdrant
    image: "qdrant/qdrant:v1.12.1"
    ports:
      - "6333:6333"
    restart: always
    environment:
      - QDRANT__SERVICE__HOST=0.0.0.0
    volumes:
      - ./data/qdrant:/qdrant/storage
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      - sclab-network

  webapp:
    container_name: webapp
    hostname: webapp
    image: "873379329511.dkr.ecr.ap-northeast-2.amazonaws.com/sclabio/onpremise-webapp:latest"
    restart: always
    ports:
      - "80"
    volumes:
      - /mnt/nfs_share/data/webapp:/data
      - /mnt/nfs_share/data/webapp/logs:/data/logs
      - /mnt/nfs_share/data/webapp/files:/data/files
      - /mnt/nfs_share/jwt:/data/jwt
      - /mnt/nfs_share/cert:/data/cert
    env_file:
      - ./common.env
      - ./webapp.env
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis
      - qdrant
    networks:
      - sclab-network

  gis-process:
    container_name: gis-process
    hostname: gis-process
    image: "873379329511.dkr.ecr.ap-northeast-2.amazonaws.com/sclabio/onpremise-gis-process:latest"
    restart: always
    volumes:
      - /mnt/nfs_share/data/gis-process/logs:/data/logs
    env_file:
      - ./common.env
      - ./gis-process.env
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis
    networks:
      - sclab-network

  mqtt-client:
    container_name: mqtt-client
    hostname: mqtt-client
    image: "873379329511.dkr.ecr.ap-northeast-2.amazonaws.com/sclabio/onpremise-mqtt-client:latest"
    restart: always
    volumes:
      - /mnt/nfs_share/data/mqtt-client/logs:/data/logs
    env_file:
      - ./common.env
      - ./mqtt-client.env
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis
    networks:
      - sclab-network
      
  mqtt-broker:
    container_name: mqtt-broker
    hostname: mqtt-broker
    image: "873379329511.dkr.ecr.ap-northeast-2.amazonaws.com/sclabio/onpremise-mqtt-broker:latest"
    restart: always
    ports:
      - "8883:8883"
      - "8888:8888"
    volumes:
      - /mnt/nfs_share/data/mqtt-broker/logs:/data/logs
      - /mnt/nfs_share/cert:/data/cert
      - /mnt/nfs_share/jwt:/data/jwt
    env_file:
      - ./common.env
      - ./mqtt-broker.env
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis
    networks:
      - sclab-network
      
  kafka-client:
    container_name: kafka-client
    hostname: kafka-client
    image: "873379329511.dkr.ecr.ap-northeast-2.amazonaws.com/sclabio/onpremise-kafka-client:latest"
    restart: always
    volumes:
      - /mnt/nfs_share/data/kafka-client/logs:/data/logs
    env_file:
      - ./common.env
      - ./kafka-client.env
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis
    networks:
      - sclab-network
  
  ai-service:
    container_name: ai-service
    hostname: ai-service
    image: "873379329511.dkr.ecr.ap-northeast-2.amazonaws.com/sclabio/onpremise-ai-service:latest"
    restart: always
    volumes:
      - /mnt/nfs_share/data/ai-service/logs:/app/dist/utils/data/logs
    env_file:
      - ./common.env
      - ./ai-service.env
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    depends_on:
      - mongo
      - redis
      - qdrant
    networks:
      - sclab-network
      
  sclab-proxy:
    container_name: sclab-proxy
    hostname: sclab-proxy
    image: nginx:alpine3.18
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    depends_on:
      - webapp
    links:
      - webapp
    networks:
      - sclab-network
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

networks:
  sclab-network:
    external: true
