# include:
#   - compose.observability.yaml
services:
  speaches:
    extends:
      file: compose.yaml
      service: speaches
    image: ghcr.io/speaches-ai/speaches:latest-cpu
    build:
      args:
        BASE_IMAGE: ubuntu:24.04

networks:
  sclab-network:
    external: true