services:
  mail:
    image: "bytemark/smtp"
    restart: always
    networks:
      - sclab-network

  webapp:
    image: "873379329511.dkr.ecr.ap-northeast-2.amazonaws.com/sclabio/onpremise-webapp:latest"
    restart: always
    ports:
      - "80"
    volumes:
      - /mnt/nfs_share/data/webapp:/data
      - /mnt/nfs_share/data/webapp/logs:/data/logs
      - /mnt/nfs_share/data/webapp/files:/data/files
      - /mnt/nfs_share/jwt:/data/jwt
      - /mnt/nfs_share/cert:/data/cert
    env_file:
      - ./common.env
      - ./webapp.env
    environment:
      - METEOR_SETTINGS=${METEOR_SETTINGS}
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      - sclab-network
      
  sclab-proxy:
    image: nginx:alpine3.18
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    depends_on:
      - webapp
    networks:
      - sclab-network
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"

networks:
  sclab-network:
    external: true
