services:
  ollama:
    image: ollama/ollama:rocm
    ports:
      - 11434:11434
    volumes:
      - ./data:/root/.ollama
    container_name: ollama
    hostname: ollama
    tty: true
    restart: 'unless-stopped'
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_MAX_LOADED_MODELS=0
      - OLLAMA_KEEP_ALIVE=-1
      - OLLAMA_MAX_QUEUE=512
      - OLLAMA_NUM_PARALLEL=1
    networks:
      - sclab-network
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"  
    devices:
      - "/dev/kfd"
      - "/dev/dri"

networks:
  sclab-network:
    external: true