version: "3.9"

services:
  # ======== OLLAMA (내부 전용) ========
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    hostname: ollama
    tty: true
    restart: unless-stopped
    volumes:
      - ./data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_MAX_LOADED_MODELS=0
      - OLLAMA_KEEP_ALIVE=-1
      - OLLAMA_MAX_QUEUE=512
      - OLLAMA_NUM_PARALLEL=1
      # - OLLAMA_ORIGINS=https://yourdomain.com
    networks:
      - sclab-network
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"

  # ======== CADDY (HTTPS + API Key 게이트) ========
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=yourdomain.com
      - API_KEY=YOUR_SUPER_SECRET_KEY
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - sclab-network
    depends_on:
      - ollama

networks:
  sclab-network:
    external: true

volumes:
  caddy_data:
  caddy_config:
